version: '3.8'

services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:80
    depends_on:
      - db-postgres
      #- db-mysql

  db-postgres:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-postgres-password
    volumes:
      - db-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres_bb
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-postgres-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  #db-mysql:
  #  image: mysql
  #  restart: always
  #  user: mysql
  #  environment:
  #    MYSQL_DATABASE: mysql_bb
  #    MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-mysql-root-password
  #  secrets:
  #    - db-mysql-root-password
  #  expose:
  #    - 3306
  #  healthcheck:
  #    test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
  #    interval: 10s
  #    timeout: 5s
  #    retries: 5

volumes:
  db-postgres-data:
  #db-mysql-data:

secrets:
  db-postgres-password:
    file: db/postgres-password.txt
  #db-mysql-root-password:
  #  file: db/mysql-root-password.txt


